### Variables
@baseUrl = http://localhost:9092

### Login
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}",
  "rememberMe": true
}

### Forgot Password
POST {{baseUrl}}/admin/forgot-password
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}"
}